version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: nbgms-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: nbgms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nbgms_user -d nbgms"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: