-- CreateEnum
CREATE TYPE "ItemStatus" AS ENUM ('GOOD_CONDITION', 'BORROWED', 'UNDER_REPAIR', 'DAMAGED', 'LOST', 'FOR_DISPOSAL', 'DISPOSED', 'RESERVED');

-- AlterTable
ALTER TABLE "InventoryItem" ADD COLUMN     "status" "ItemStatus" NOT NULL DEFAULT 'GOOD_CONDITION';
